### ISSUE TITLE
When using LDAP to provide the certificates, users are always set to type "client"

### ISSUE THREAD

**Issue by sophiebella28** [hyperledger/fabric-ca#378]
I have recently been trying to configure a connection between the LDAP server that we use for storing user credentials and the fabric-ca server. In our configuration, we are using NodeOUs to determine user permissions - when not using LDAP, and registering with the ca directly, we set this using the -type flag set to one of admin, peer, client or orderer. However, it seems that when using LDAP configuration, the user is always set to a default of type client, which cannot be changed through any LDAP attributes or API calls. 

This makes the LDAP configuration with the ca unusable if you want to have any sort of policies set up requiring type admin/peer/orderer, as the certificate always identifies it as type client. Here is a link to a stackoverflow post where they had the same issue, for added context on the issue -  https://stackoverflow.com/questions/63834220/set-admin-role-for-an-ldap-user-in-hyperledger-fabric-ca. 

I'm pretty sure that this can easily be fixed by just editing the file `fabric-ca/lib/server/ldap/client.go`, specifically the getType function on line 342 - just adding an attribute lookup in LDAP for an attribute Type or something similar, and then if that value exists return it, otherwise still defaulting to client.

If there is a way to set the type of a user when getting the details from LDAP, please let me know!

**Comment by antcybersec** [comment]
Hi — I'd like to work on this issue and wanted to share my analysis (including the Stack Overflow thread) and get maintainer feedback on the proposed approach before opening a PR.

---

## Problem summary

When Fabric CA is configured to use LDAP, every enrolled identity gets identity type **`client`**, regardless of LDAP group membership or attribute converters. That breaks deployments using **NodeOUs** where certificates need OU values like `admin`, `peer`, or `orderer` for MSP policy checks (e.g. chaincode install requires `Admins` principal).

With non-LDAP registration, type is set via `--id.type` at register time. With LDAP, there is currently no equivalent path.

---

## Related community reports

### GitHub #378 (this issue)

@sophiebella28 reported the same limitation: NodeOU-based policies don't work for LDAP users because type is hardcoded to `client`, and it can't be changed via LDAP attributes or API calls. The suggested fix was to update `GetType()` in `lib/server/ldap/client.go` to read a type from LDAP (e.g. a `Type` attribute) with fallback to `client`.

### [Stack Overflow — Set admin role for an LDAP user in Hyperledger Fabric CA](https://stackoverflow.com/questions/63834220/set-admin-role-for-an-ldap-user-in-hyperledger-fabric-ca) (Sep 2020, updated May 2024)

**Reporter (Ana Franco)** — Active Directory + LDAP, needs `user` vs `admin` roles:

- Mapped AD `memberOf` to `hf.Registrar.Roles` via converters/maps:

```yaml
ldap:
  attribute:
    names: ['userPrincipalName','memberOf']
    converters:
      - name: hf.Revoker
        value: attr("userPrincipalName") =~ "revoker*"
      - name: hf.Registrar.Roles
        value: map(attr("memberOf"),"roles")
    maps:
      roles:
        - name: CN=BC-CLIENT,DC=ORG1,DC=com
          value: client
        - name: CN=BC-USER,DC=ORG1,DC=com
          value: user
        - name: CN=BC-ADMIN,DC=ORG1,DC=com
          value: admin
        - name: CN=BC-PEER,DC=ORG1,DC=com
          value: peer
        - name: CN=BC-ORDERER,DC=ORG1,DC=com
          value: orderer
```

- Enrollment succeeded; query/invoke worked.
- **Chaincode install failed** with:

  > The identity does not contain OU [ADMIN], MSP: [Org1MSP]

- CA logs showed `hf.Registrar.Roles` mapping worked, but that attribute does **not** control the identity type OU on the certificate.

**Follow-up attempt** — added a converter for `OU`:

```yaml
converters:
  - name: OU
    value: map(attr("memberOf"),"roles")
```

CA logs showed evaluation working (`result: client,admin,user`), but install still failed — **custom attribute converters don't set the enrollment identity type OU**.

**Reporter conclusion:** Certificate from LDAP always gets `OU=client`; you can't change it via converters. Workaround of remapping NodeOU identifiers to LDAP OU values only works if you control LDAP OUs, not just `memberOf`.

**Accepted answer (yacovm):** Certificate must contain the OU that defines admin per MSP `config.yaml`; alternatively place cert in `admincerts` folder.

**Answer 2 (PraveenRaizo, May 2024):** Same root cause — `fabric-ca-client`/CA always generates `OU=client` in addition to LDAP-derived OUs. No fabric attribute like `hf.Registrar.Roles` controls this. **Workaround:** create custom LDAP OUs (`adminRole`, `peerRole`, etc.) and change NodeOU `OrganizationalUnitIdentifier` values in MSP `config.yaml` to match — Fabric then uses those identifiers instead of default `admin`/`peer`/`client`/`orderer`. Still leaves an extra `OU=client` on the cert, but channel join / chaincode install can work.

---

## Root cause in code

In `lib/server/ldap/client.go`, `GetType()` is hardcoded:

```go
func (u *user) GetType() string {
    return "client"
}
```

During enrollment, `lib/serverenroll.go` uses `caller.GetType()` to add the **identity type OU** to the CSR:

```go
names = append(names, csr.Name{OU: caller.GetType()})
```

So every LDAP enrollment gets `OU=client` on the certificate, regardless of `attribute.converters` (which only affect Fabric CA **attributes** like `hf.Revoker`, `hf.Registrar.Roles`, etc. — not identity type).

This is separate from affiliation OUs (derived from DN `OU=` components via `GetAffiliationPath()`).

---

## Why existing LDAP converters aren't enough

| Mechanism | What it affects | Fixes NodeOU type? |
|-----------|-----------------|-------------------|
| `attribute.converters` (e.g. `hf.Registrar.Roles`) | Custom attrs on cert / authorization | No |
| Converter named `OU` | Custom attribute named `OU` | No — not the identity type OU |
| `hf.Revoker`, `hf.Registrar.*` | CA authorization attributes | No |
| `GetType()` | Identity type → CSR `OU=<type>` | **This is what needs to change** |

---

## Proposed fix (backward compatible)

Add an optional LDAP config field to derive identity type from LDAP, reusing the existing expression language (`attr()`, `map()`, `if()`, etc.):

```yaml
ldap:
  enabled: true
  url: ldap://...
  attribute:
    names: ['uid', 'memberOf', 'employeeType']
  type: map(attr("memberOf"), "roles")   # NEW — optional
  converters:
    - name: hf.Revoker
      value: attr("uid") =~ "revoker*"
  maps:
    roles:
      - name: CN=BC-ADMIN,DC=ORG1,DC=com
        value: admin
      - name: CN=BC-PEER,DC=ORG1,DC=com
        value: peer
```

**Behavior:**
- If `ldap.attribute.type` is unset → `GetType()` returns `"client"` (current behavior, no breaking change).
- If set → evaluate expression against the LDAP entry; return result if valid (`client`, `peer`, `orderer`, `admin`, `user`, etc. per CA registry).
- Validate expression at server startup (same as other converters).
- Fall back to `"client"` if expression is empty or evaluation fails.

**Implementation sketch:**
1. Add `Type string` to `AttrConfig` in `lib/server/ldap/client.go`
2. Parse/validate type expression in `NewClient` (like `newUserExpr`)
3. Update `user.GetType()` to evaluate expression or default to `client`
4. Unit tests in `lib/server/ldap/client_test.go`
5. Document in `docs/source/users-guide.rst` (LDAP section)
6. Run `scripts/fvt/ldap_test.sh`

---

## Questions for maintainers

1. **Config shape:** Is `ldap.attribute.type` (expression string) the right API, or would you prefer a simpler plain LDAP attribute name (e.g. `typeAttribute: employeeType`) without expressions?

2. **Validation:** Should we restrict type values to the same set as `register --id.type` (`client`, `peer`, `orderer`, `admin`, `user`, …)?

3. **Multiple values:** If `map(attr("memberOf"), "roles")` returns `"client,admin,user"` (as in the SO logs), should we take the first value, error, or define precedence rules?

4. **Alternative:** Should this be a reserved converter name (e.g. internal `hf.Type`) instead of a dedicated config field?

Happy to open a PR once we align on the config format. I've contributed to this repo recently ([#502](https://github.com/hyperledger/fabric-ca/pull/502), [#506](https://github.com/hyperledger/fabric-ca/pull/506)) and am familiar with the LDAP expression path.

Thanks!
